"""new fields in user model

Revision ID: 352bd253b4b3
Revises: 57e9dee7d6a9
Create Date: 2020-08-31 14:28:29.764133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352bd253b4b3'
down_revision = '57e9dee7d6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
